export COPILOT_PROVIDER_BASE_URL="http://127.0.0.1:8080/v1"
export COPILOT_OFFLINE="true"
export COPILOT_PROVIDER_TYPE="openai"
export COPILOT_PROVIDER_MAX_PROMPT_TOKENS=65536
export COPILOT_PROVIDER_MAX_OUTPUT_TOKENS=4096
export COPILOT_MODEL="qwen3.6"
export COPILOT_PROVIDER_API_KEY="ignored"
